### PR TITLE
Constructors don't return values

### PR DESCRIPTION
**Pull request by Bilge**
If you had unit test coverage this wouldn't be news to you.

### CODE REVIEW

**Comment by Bilge** [comment]
I've also removed the `installed` method from the cache interface because that does not belong here. A cache implementation does not know whether it is "installed". However, by type hinting the dependency it is impossible to construct the cache if the dependency is not installed.

**Comment by voku** [comment]
If you edit a interface, we also have to edit all classes that used this interface. Also we use the "installed()"-methode in the main-class (`Cache.php`) ... e.g.: https://github.com/voku/simple-cache/blob/master/src/voku/cache/Cache.php#L164

**Comment by Bilge** [comment]
You're right, but I don't have time to address all the other classes. Also I think you should get rid of the "Cache" class. It's terrible code and beyond saving in my opinion. This library has value as just a cache abstraction; you definitely do not need some kind of factory that tries to auto-select an implementation; but I digress.

**Comment by voku** [comment]
But I need a auto-select for the cache implementation, because I / customers have many different servers with different cache-systems. So I must either login in every server to check what kind of cache we can use and add this into a "config", but if someone edit the server-config or move the web to another server the cache wan't work anymore ... :/

This is why I added this sentence into the README -> "... the class will auto-detect you server-cache in this order ..."

**Comment by Bilge** [comment]
Well that's great for you and your customers but you should host this as a private repository, not a public one. I no longer have any interest in contributing to this.

**Pull request closed without merging**
